#!/bin/bash --norc

PATH="external/gcc_linaro_7_3_1_arm_linux_gnueabihf/libexec/gcc/arm-linux-gnueabihf/7.3.1:$PATH" \
    exec \
    external/gcc_linaro_7_3_1_arm_linux_gnueabihf/bin/arm-linux-gnueabihf-gcc \
    "$@"
