set(CMAKE_C_COMPILER "${HEXAGON_TOOLS}/bin/hexagon-clang")
set(CMAKE_CXX_COMPILER "${HEXAGON_TOOLS}/bin/hexagon-clang")
set(CMAKE_AR "${HEXAGON_TOOLS}/bin/hexagon-ar" CACHE FILEPATH "Archiver")
set(CMAKE_LINKER ${HEXAGON_TOOLS}/bin/hexagon-link)

set(CMAKE_FIND_ROOT_PATH "${HEXAGON_SDK_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(HEXAGON ON)
set(HEXAGON8 ON)
