# Description:
# MACE public API.
#
package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "public",
    hdrs = [
        "mace.h",
        "mace_runtime.h",
    ],
    copts = ["-Werror", "-Wextra", "-Wno-missing-field-initializers"],
)
