# Description:
# MACE public API.
#
package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])  # Apache 2.0

load("//mace:mace.bzl", "if_android")

cc_library(
    name = "public",
    hdrs = [
        "mace.h",
    ],
)
