py_library(
    name = "visualization_lib",
    srcs = [
        "visualize_model.py",
    ],
    data = [
        "index.html",
    ],
    srcs_version = "PY2AND3",
    visibility = ["//visibility:public"],
    deps = [
        "//mace/proto:mace_py",
    ],
)
